name: Integration Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        test_name:
        - test_Spin_up_and_destroy_simple_virtual_machine
        - test_Spin_up_simple_virtual_machine-2c_provision_via_shell
        - test_Spin_up_simple_virtual_machine_with_custom_default-2d5fprefix
        - test_Spin_up_virtual_machine_with_second_disk
        - test_Spin_up_virtual_machine-2c_adjust_memory_settings
        - test_Spin_up_virtual_machine-2c_adjust_cpu_settings
        - test_Spin_up_virtual_machine-2c_add_private_network-2c_check_if_IP_is_reachable

    env:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
      VAGRANT_VERSION: v2.2.14

    steps:
    - uses: actions/checkout@v2
    - name: Set up libvirt
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          bridge-utils \
          dnsmasq-base \
          ebtables \
          libvirt-clients \
          libvirt-daemon \
          qemu-kvm \
          qemu-utils \
          libarchive-tools \
        ;
        sudo apt-get install \
          libvirt-dev \
          libz-dev \
        ;
        sudo apt-get install \
          bats \
          fping \
        ;

        sudo systemctl list-unit-files
        sudo systemctl start libvirt
    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-
    - uses: actions/cache@v2
      with:
        path: ~/.vagrant.d/boxes
        key: ${{ runner.os }}-${{ env.VAGRANT_VERSION }}
        restore-keys: |
          ${{ runner.os }}-
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.6.6
    - name: Set up rubygems
      run: |
        gem update --system --conservative || (gem i "rubygems-update:~>2.7" --no-document && update_rubygems)
        gem update bundler --conservative
    - name: Run bundler using cached path
      run: |
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
    - name: Install binstubs
      run: |
        bundle binstubs --all --path=/tmp/exec 1>/dev/null
        /tmp/exec/vagrant --version
    - name: Run tests
      run: |
        ./tests/one_test.sh ./tests/runtests.bats ${{ matrix.test_name }}
